workflows:
  android-capacitor:
    name: Android Capacitor Debug APK
    max_build_duration: 60

    environment:
      node: 22
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build web
        script: |
          npm run build

      - name: Force add Android platform
        script: |
          rm -rf android
          npx cap add android

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Verify gradlew exists
        script: |
          ls -la android
          ls -la android/gradlew

      - name: Build Debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
